adminapp/urls.py
from django.contrib import admin
from django.urls import path, include
from adminapp import views as adminapp

app_name = 'adminapp'

urlpatterns = [
    path('', adminapp.UsersListView.as_view(), name='users'),
    path('users/create/', adminapp.UsersCreateView.as_view(), name='user_create'),
    path('users/update/<int:pk>/', adminapp.UserUpdateView.as_view(), name='user_update'),
    path('users/delete/<int:pk>/', adminapp.UserDeleteView.as_view(), name='user_delete'),

    path('categories/', adminapp.CategoryListView.as_view(), name='categories'),
    path('categories/create/', adminapp.CategoryCreateView.as_view(), name='category_create'),
    path('categories/update/<int:pk>/', adminapp.CategoryUpdateView.as_view(), name='category_update'),
    path('categories/delete/<int:pk>/', adminapp.CategoryDeleteView.as_view(), name='category_delete'),

    path('products/<int:pk>/', adminapp.ProductsListView.as_view(), name='products'),
    path('products/<int:pk>/create/', adminapp.ProductCreateView.as_view(), name='product_create'),
    path('products/<int:category_pk>/update/<int:pk>/', adminapp.ProductUpdateView.as_view(), name='product_update'),
    path('products/<int:category_pk>/delete/<int:pk>/', adminapp.ProductDeleteView.as_view(), name='product_delete'),
    path('products/<int:category_pk>/read/<int:pk>/', adminapp.ProductDetailView.as_view(), name='product_read'),

]

authapp/urls.py
from django.urls import path
from authapp import views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('edit/', authapp.edit, name='edit'),
    path('register/', authapp.register, name='register'),
    path('verify/<email>/<activation_key>', authapp.verify, name='verify')
]

geekshop/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include, re_path
from mainapp import views as mainapp

urlpatterns = [
    path('', mainapp.IndexView.as_view(), name='index'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('contact/', mainapp.ContactsView.as_view(), name='contact'),
    path('auth/', include('authapp.urls', namespace='authapp')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('admin/', include('adminapp.urls', namespace='adminapp')),
    path('orders/', include('ordersapp.urls', namespace='ordersapp')),
    re_path('', include("social_django.urls", namespace="social")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    import debug_toolbar
    urlpatterns += [re_path(r'^__debug__/', include(debug_toolbar.urls))]

adminapp/models.py
from django.db import models

# Create your models here.

adminapp/forms.py
from django import forms

from authapp.forms import ShopUserEditForm
from authapp.models import ShopUser
from mainapp.models import ProductCategory, Product


class ShopUserAdminEditForm(ShopUserEditForm):

    class Meta:
        model = ShopUser
        fields = '__all__'


class ProductCategoryForm(forms.ModelForm):
    discount = forms.IntegerField(label='Скидка', required=False, min_value=0, max_value=90, initial=0)

    class Meta:
        model = ProductCategory
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class ProductForm(forms.ModelForm):

    class Meta:
        model = Product
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

adminapp/views.py
from django.contrib.auth.decorators import user_passes_test
from django.core.exceptions import ImproperlyConfigured
from django.db.models import QuerySet, F
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404

# Create your views here.
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView

from adminapp.forms import ShopUserAdminEditForm, ProductCategoryForm, ProductForm
from authapp.forms import ShopUserRegisterForm
from authapp.models import ShopUser
from mainapp.models import ProductCategory, Product


class UsersListView(ListView):
    model = ShopUser
    template_name = 'adminapp/users_list.html'
    ordering = '-is_active'

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)


class UsersCreateView(CreateView):
    model = ShopUser
    form_class = ShopUserRegisterForm
    template_name = 'adminapp/user_form.html'
    success_url = reverse_lazy('adminapp:users')


class UserUpdateView(UpdateView):
    model = ShopUser
    form_class = ShopUserRegisterForm
    template_name = 'adminapp/user_form.html'
    success_url = reverse_lazy('adminapp:users')


class UserDeleteView(DeleteView):
    model = ShopUser
    template_name = 'adminapp/user_delete.html'
    success_url = reverse_lazy('adminapp:users')


class CategoryListView(ListView):
    model = ProductCategory
    template_name = 'adminapp/categories_list.html'
    ordering = '-is_active'


class CategoryCreateView(CreateView):
    model = ProductCategory
    template_name = 'adminapp/categories_form.html'
    form_class = ProductCategoryForm
    success_url = reverse_lazy('adminapp:categories')


class CategoryUpdateView(UpdateView):
    model = ProductCategory
    template_name = 'adminapp/categories_form.html'
    form_class = ProductCategoryForm
    success_url = reverse_lazy('adminapp:categories')

    def form_valid(self, form):
        if 'discount' in form.cleaned_data:
            discount = form.cleaned_data['discount']
            if discount:
                self.object.product_set.update(price=F('price') * (1 - discount/100))
        return super().form_valid(form)


class CategoryDeleteView(DeleteView):
    model = ProductCategory
    template_name = 'adminapp/category_delete.html'
    success_url = reverse_lazy('adminapp:categories')


class ProductsListView(ListView):
    model = Product
    template_name = 'adminapp/products_list.html'

    def _getcategory(self):
        category_id = self.kwargs.get('pk')
        category = get_object_or_404(ProductCategory, pk=category_id)
        return category

    def get_queryset(self):
        return Product.objects.all().filter(category__pk=self._getcategory().pk).order_by('-is_active')


class ProductCreateView(CreateView):
    model = Product
    form_class = ProductForm
    template_name = 'adminapp/product_form.html'
    success_url = reverse_lazy('adminapp:categories')

    def _getcategory(self):
        category_id = self.kwargs.get('pk')
        category = get_object_or_404(ProductCategory, pk=category_id)
        return category

    def get_success_url(self):
        return reverse('adminapp:products', args=[self._getcategory().pk])

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        if self.request.method == 'GET':
            context_data['category'] = self._getcategory()
        return context_data


class ProductUpdateView(UpdateView):
    model = Product
    form_class = ProductForm
    template_name = 'adminapp/product_form.html'
    success_url = reverse_lazy('adminapp:categories')

    def _getcategory(self):
        category_id = self.kwargs.get('category_pk')
        category = get_object_or_404(ProductCategory, pk=category_id)
        return category

    def get_success_url(self):
        return reverse('adminapp:products', args=[self._getcategory().pk])

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        if self.request.method == 'GET':
            context_data['category'] = self._getcategory()
        return context_data


class ProductDeleteView(DeleteView):
    model = Product
    template_name = 'adminapp/product_delete.html'
    success_url = reverse_lazy('adminapp:products')

    def _getcategory(self):
        category_id = self.kwargs.get('category_pk')
        category = get_object_or_404(ProductCategory, pk=category_id)
        return category

    def get_success_url(self):
        return reverse('adminapp:products', args=[self._getcategory().pk])

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        if self.request.method == 'GET':
            context_data['category'] = self._getcategory()
        return context_data


class ProductDetailView(DetailView):
    model = Product
    template_name = 'adminapp/product.html'

adminapp/templates/adminapp/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Панель администратора</title>
    {% block css %}
	    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
	    <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/font-awesome.css' %}">
    {% endblock %}
</head>
<body>
<div class="admin_container">
    <div class="h2 text-center head">
        Панель администратора
    </div>
    {% block menu %}
        <div class="admin_menu">
            {% include 'adminapp/includes/inc_menu.html' %}
        </div>
    {% endblock %}

    {% block content %}
    {% endblock %}
</div>
</body>
</html>

adminapp/templates/adminapp/categories_form.html
{% extends 'adminapp/base.html' %}

{% block content %}
    <div class="container">
        <form class="form-horizontal" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" class="btn btn-primary" value="Сохранить">
        </form>
        <a href="{% url 'adminapp:categories' %}">К списку категорий</a>
    </div>
{% endblock %}

adminapp/templates/adminapp/categories_list.html
{% extends 'adminapp/base.html' %}

{% block content %}
    <div class="categories_list">
        <button class="new_category">
            <a href="{% url 'adminapp:category_create' %}">Новая категория</a>
        </button>
        {% for item in object_list %}
            <div class="category_record" {% if not item.is_active %}style="opacity: 0.5"{% endif %}>
                <div class="category_name">{{ item.name|title }}</div>
                {% if item.is_active %}
                    <div class="category_actions">
                        <button style="width: 170px">
                            <a href="{% url 'adminapp:products' item.pk %}">Товары категории</a>
                        </button>
                        <button style="width: 170px">
                            <a href="{% url 'adminapp:category_update' item.pk %}">Изменить</a>
                        </button>
                        <button style="width: 170px">
                            <a href="{% url 'adminapp:category_delete' item.pk %}">Удалить</a>
                        </button>
                    </div>
                    <div class="category_desc">{{ item.description|capfirst }}</div>
                {% else %}
                    <div class="category_desc">Архивная категория (Удалена)</div>
                {% endif %}
            </div>
        {% endfor %}
    </div>
{% endblock %}

adminapp/templates/adminapp/category_delete.html
{% extends 'adminapp/base.html' %}

{% block content %}
    <div class="container">
    <p>Вы уверены что хотите удалить категорию "{{ object.name }}"?</p>
    <form method="post">
        {% csrf_token %}
        <input type="submit" value="Подтвердить" class="user_delete" style="width: 200px"><br>
        <a href="{% url 'adminapp:categories' %}" class="btn btn-primary">Отмена</a>
    </form>
    </div>
{% endblock %}

adminapp/templates/adminapp/product.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
  <div class="product_read">
    <div class="product_name">
      Продукт<strong>{{ product.category.name|title }} /
                     {{ product.name|title }}</strong>
    </div>
    <img src="/media/{{ product.image|default:'products_images/default.jpg' }}"
         alt="{{ product.name }}">
    <div class="summary">
      <b>цена</b>
      <p>{{ product.price }} руб</p>
      <b>количество</b>
      <p>{{ product.quantity }}</p>
      <b>в каталоге</b>
      <p>{% if product.is_active %}да{% else %}нет{% endif %}</p>
      <p>
        <button>
          <a href={% url 'adminapp:product_update' product.category.pk product.pk %}>
            редактировать
          </a>
        </button>
      </p>
      <p>
        <button>
          <a href={% url 'adminapp:product_delete' product.category.pk product.pk %}>
            удалить
          </a>
        </button>
      </p>
      <p>
        <button>
          <a href={% url 'adminapp:products' product.category.pk %}>
            назад
          </a>
        </button>
      </p>
    </div>
    <div class="product_desc">
      <b>краткая информация</b>
      <p>{{ product.short_desc }}</p>
      <br><br>
      <b>подробная информация</b>
      <p>{{ product.description }}</p>
    </div>
  </div>
{% endblock %}

adminapp/templates/adminapp/product_delete.html
{% extends 'adminapp/base.html' %}

{% block content %}
    <div class="container">
    <p>Вы уверены что хотите удалить продукт "{{ object.name }}"?</p>
    <form method="post">
        {% csrf_token %}
        <input type="submit" value="Подтвердить" class="user_delete" style="width: 200px"><br>
        <a href="{% url 'adminapp:products' category.pk %}" class="btn btn-primary">Отмена</a>
    </form>
    </div>
{% endblock %}

adminapp/templates/adminapp/product_form.html
{% extends 'adminapp/base.html' %}

{% block content %}
    <div class="container">
        <form class="form-horizontal" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" class="btn btn-primary" value="Сохранить">
        </form>
        <a href="{% url 'adminapp:products' category.pk %}">К списку товаров категории "<span>{{ category.name }}</span>"</a>
    </div>
{% endblock %}

adminapp/templates/adminapp/products_list.html
{% extends 'adminapp/base.html' %}
{% load my_tags %}

{% block content %}
    <div class="products_list">
        <button class="new_product">
            <a href="{% url 'adminapp:product_create' object_list.0.category.pk %}">Новый продукт</a>
        </button>
        {% for item in object_list %}
            <div class="product_record" {% if not item.is_active %}style="opacity: 0.5" {% endif %}>
                <div class="product_name">{{ item.name|capfirst }}</div>
                <img src="{{ item.image|media_for_products }}" alt="">
                {% if item.is_active %}
                    <div class="product_actions">
                        <button>
                            <a href="{% url 'adminapp:product_update' item.category.pk item.pk %}">Изменить</a>
                        </button>
                        <button>
                            <a href="{% url 'adminapp:product_delete' item.category.pk item.pk %}">Удалить</a>
                        </button>
                        <button>
                            <a href="{% url 'adminapp:product_read' item.category.pk item.pk %}">Просмотреть</a>
                        </button>
                    </div>
                {% endif %}
                <div class="summary" style="width: 150px">
                    <span class="product_cost">Цена: {{ item.price }} руб.</span> <br>
                    Кол-во: {{ item.quantity }} шт.
                </div>
                <div class="product_desc">{{ item.description }}</div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

adminapp/templates/adminapp/user_delete.html
{% extends 'adminapp/base.html' %}

{% block content %}
    <div class="container">
    <p>Вы уверены что хотите удалить пользователя {{ object.username }}?</p>
    <form method="post">
        {% csrf_token %}
        <input type="submit" value="Подтвердить" class="user_delete" style="width: 200px"><br>
        <a href="{% url 'adminapp:users' %}" class="btn btn-primary">Отмена</a>
    </form>
    </div>
{% endblock %}

adminapp/templates/adminapp/user_form.html
{% extends 'adminapp/base.html' %}

{% block content %}
    <div class="container">
        <form class="form-horizontal" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" class="btn btn-primary" value="Сохранить">
        </form>
        <a href="{% url 'adminapp:users' %}">К списку пользователей</a>
    </div>
{% endblock %}

adminapp/templates/adminapp/users_list.html
{% extends 'adminapp/base.html' %}
{% load my_tags %}

{% block content %}
    <div class="users_list">
        <button class="new_user">
            <a href="{% url 'adminapp:user_create' %}">Новый пользователь</a>
        </button>
        {% for item in object_list %}
            <div class="user_record" {% if not item.is_active %}style="opacity: 0.5" {% endif %}>
                <img src="{{ item.avatar|media_for_users }}" alt="{{ item.username }}" width="150px">
                <div class="user_role">
                    {% if item.is_superuser %}
                        Администратор
                    {% else %}
                        Пользователь
                    {% endif %}
                    {% if item.is_active %}
                        <button>
                            <a href="{% url 'adminapp:user_update' item.pk %}">Изменить</a>
                        </button>
                    {% endif %}
                    {% if item.is_active and not item.is_superuser %}
                        <button>
                            <a href="{% url 'adminapp:user_delete' item.pk %}">Удалить</a>
                        </button>
                    {% endif %}
                </div>
                <div class="user_name">
                    <p>{{ item.username }}</p>
                    <p>{{ item.get_full_name }}</p>
                </div>
                <div class="user_age">
                    {{ item.age }} лет
                </div>
                <div class="user_email">{{ item.email }}</div>
            </div>

        {% endfor %}
    </div>
{% endblock %}