authapp/urls.py
from django.urls import path
from authapp import views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('edit/', authapp.edit, name='edit'),
    path('register/', authapp.register, name='register'),
    path('verify/<email>/<activation_key>', authapp.verify, name='verify')
]

basketapp/urls.py
from django.contrib import admin
from django.urls import path, include
from basketapp import views as basketapp

app_name = 'basketapp'

urlpatterns = [
    path('', basketapp.basket, name='basket'),
    path('add/<int:pk>', basketapp.basket_add, name='basket_add'),
    path('remove/<int:pk>', basketapp.basket_remove, name='basket_remove'),
    path('edit/<int:pk>/<quantity>/', basketapp.basket_edit, name='basket_edit')
]

geekshop/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include, re_path
from mainapp import views as mainapp

urlpatterns = [
    path('', mainapp.IndexView.as_view(), name='index'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('contact/', mainapp.ContactsView.as_view(), name='contact'),
    path('auth/', include('authapp.urls', namespace='authapp')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('admin/', include('adminapp.urls', namespace='adminapp')),
    path('orders/', include('ordersapp.urls', namespace='ordersapp')),
    re_path('', include("social_django.urls", namespace="social")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    import debug_toolbar
    urlpatterns += [re_path(r'^__debug__/', include(debug_toolbar.urls))]

mainapp/urls.py
from django.urls import path
from mainapp import views as mainapp

app_name = 'products'

urlpatterns = [
    path('', mainapp.products, name='products'),
    path('<int:pk>/', mainapp.products, name='category'),
    path('<int:pk>/<int:page>', mainapp.products, name='product_paginate'),
    path('product/<int:pk>', mainapp.ProductView.as_view(), name='product'),
]

mainapp/models.py
from django.db import models


class ProductCategory(models.Model):
    name = models.CharField(max_length=64, unique=True, verbose_name='имя')
    description = models.TextField(blank=True, verbose_name='описание')
    is_active = models.BooleanField(default=True, verbose_name='активен')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'категории'

    def delete(self, *args, **kwargs):
        self.is_active = False
        self.save()


class Product(models.Model):
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE, verbose_name='категория')
    name = models.CharField(max_length=128, verbose_name='имя продукта')
    image = models.ImageField(upload_to='products_images', blank=True, verbose_name='изображение')
    short_desc = models.CharField(max_length=60, blank=True, verbose_name='краткое описание продукта')
    description = models.TextField(blank=True, verbose_name='описание продукта')
    price = models.DecimalField(max_digits=8, decimal_places=2, default=0, verbose_name='цена продукта')
    quantity = models.PositiveIntegerField(default=0, verbose_name='количество на складе')
    is_active = models.BooleanField(default=True, verbose_name='активен')

    def __str__(self):
        return f'{self.name} ({self.category.name})'

    class Meta:
        verbose_name = 'продукт'
        verbose_name_plural = 'продукты'

    def delete(self, *args, **kwargs):
        self.is_active = False
        self.save()

    @classmethod
    def get_items(cls):
        pass

mainapp/views.py
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.shortcuts import render, get_object_or_404
from django.conf import settings
import json

from django.views.decorators.cache import cache_page
from django.views.generic import ListView

from mainapp.models import Product, ProductCategory
from services import get_hot_product, get_same_products
from django.core.cache import cache


def get_links_menu():
    if settings.LOW_CACHE:
        key = 'links_menu'
        links_menu = cache.get(key)
        if links_menu is None:
            links_menu = ProductCategory.objects.filter(is_active=True)
            cache.set(key, links_menu)
        return links_menu
    else:
        return ProductCategory.objects.filter(is_active=True)


def get_category(pk):
    if settings.LOW_CACHE:
        key = f'category_{pk}'
        category = cache.get(key)
        if category is None:
            category = get_object_or_404(ProductCategory, pk=pk)
            cache.set(key, category)
        return category
    else:
        return get_object_or_404(ProductCategory, pk=pk)


def get_products():
    if settings.LOW_CACHE:
        key = 'products'
        products = cache.get(key)
        if products is None:
            products = Product.objects.filter(is_active=True, category__is_active=True).select_related('category')
            cache.set(key, products)
        return products[1:5]
    else:
        return Product.objects.filter(is_active=True, category__is_active=True).select_related('category')


def get_product(pk):
    if settings.LOW_CACHE:
        key = f'product_{pk}'
        product = cache.get(key)
        if product is None:
            product = get_object_or_404(Product, pk=pk)
            cache.set(key, product)
        return product
    else:
        return get_object_or_404(Product, pk=pk)


def get_products_in_category_ordered_by_price(pk):
    if settings.LOW_CACHE:
        key = f'products in category_ordered_by_price_{pk}'
        products = cache.get(key)
        if products is None:
            products = Product.objects.filter(category__pk=pk, is_active=True, category__is_active=True). \
                order_by('price')
            cache.set(key, products)
            return products
        else:
            return Product.objects.filter(category__pk=pk, is_active=True, category__is_active=True).order_by('price')


class IndexView(ListView):
    model = Product
    template_name = 'mainapp/index.html'

    def get_queryset(self):
        # return super(IndexView, self).get_queryset().filter(is_active=True).select_related()[:4]
        return get_products().select_related()

    def get_context_data(self, *, object_list=None, **kwargs):
        context_data = super(IndexView, self).get_context_data()
        context_data['title'] = 'Мой магазин'
        return context_data


@cache_page(3600)
def products(request, pk=None, page=1):
    links_products_menu = get_links_menu()
    hot_product = get_hot_product()

    if pk is not None:
        if pk == 0:
            products_list = get_products()
            category_item = {'name': 'Все', 'pk': 0}
        else:
            category_item = get_category(pk=pk)
            products_list = Product.objects.filter(category__pk=pk).filter(is_active=True)

        paginator = Paginator(products_list, 2)
        try:
            products_paginator = paginator.page(page)
        except PageNotAnInteger:
            products_paginator = paginator.page(1)
        except EmptyPage:
            products_paginator = paginator.page(paginator.num_pages)

        context = {
            'links_products_menu': links_products_menu,
            'products': products_paginator,
            'category': category_item
        }
        return render(request, 'mainapp/products_list.html', context)
    context = {
        'links_products_menu': links_products_menu,
        'title': 'Товары',
        'hot_product': hot_product,
        'same_products': get_same_products(hot_product)
    }
    return render(request, 'mainapp/products.html', context)


class ContactsView(ListView):
    template_name = 'mainapp/contact.html'

    def get_queryset(self):
        return

    def get_context_data(self, *, object_list=None, **kwargs):
        with open(f'{settings.BASE_DIR}/contacts.json') as contacts_file:
            context_data = {
                'contacts': json.load(contacts_file)
            }
        return context_data


class ProductView(ListView):
    template_name = 'mainapp/product.html'

    def get_queryset(self):
        return

    def get_context_data(self, *, object_list=None, **kwargs):
        context_data = {
            'product': get_product(pk=self.kwargs.get('pk')),
            'links_products_menu': get_links_menu()
        }
        return context_data

mainapp/templates/mainapp/base.html
{% load static %}
<!DOCTYPE html>
<html lang="">
<head>
	<meta charset="utf-8">
	<title>{{ title|default:"Магазин" }}</title>
    {% block css %}
	    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
	    <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/font-awesome.css' %}">
    {% endblock %}
</head>
<body>
	<div class="container">
        {% block content %}
        {% endblock %}
		<div class="clr"></div>

	</div>
{% block footer %}
    <div class="footer">
        <div class="clearfix">
            <div class="text-footer">
                <h3>контакты</h3>
            </div>
            <div class="text-footer">
                <h3>полезная информация</h3>
            </div>
            <div class="text-footer clearfix">
                <h3>Оставайтесь на связи</h3>
                <p>Подписаться на новости и рассылки</p>
                <form>
                    <label>
                        <input type="email" name="email" placeholder="ваш email">
                    </label>
                    <a href="#"><i class="fa fa-paper-plane fa-2x" aria-hidden="true"></i></a>
                </form>
            </div>
        </div>
        <p class="small">&copy; {% now 'Y' %}</p>
        <div class="social">
            <a href="#" class="social1"></a>
            <a href="#" class="social2"></a>
            <a href="#" class="social3"></a>
            <a href="#" class="social4"></a>
        </div>
        <p class="small">Положения &amp; Условия  /  Конфиденциальность &amp; Cookies</p>
    </div>
{% endblock %}

</body>
</html>

mainapp/templates/mainapp/contact.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% block content %}
<div class="hero">
	<div class="header clearfix">
		{% include 'mainapp/includes/inc_main_menu.html' %}
	</div>
	<h1>наши контакты</h1>
</div>
<div class="location">
	{% for contact in contacts %}
	<div class="location-1">
		<i class="fa fa-map-marker fa-5x"></i>
		<h4>{{ contact.city }}</h4>
		<div class="contacts">
			<h5>Телефон</h5>
			<p>{{ contact.phone }}</p>
		</div>
		<div class="contacts">
			<h5>Email</h5>
			<p>{{ contact.email }}</p>
		</div>
		<div class="contacts">
			<h5>Адрес</h5>
			<p>{{ contact.address }}</p>
		</div>
	</div>
	{% endfor %}
</div>
{% endblock %}

mainapp/templates/mainapp/index.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% block content %}
<div class="slider">
    <div class="header clearfix">
        {% include 'mainapp/includes/inc_main_menu.html' %}
    </div>
    <div class="text-slider">
        <h3 class="green">тенденции</h3>
        <h3 class="big"> удобные стулья</h3>
        <p>Новый уровень комфорта. Отличные характеристики.</p>
        <a href="#" class="button-order">заказать <img src="{% static 'img/arrow.png' %}" alt=""></a>
    </div>
    <div class="navi">
        <a href="#"></a><a href="#"></a><a href="#"></a>
    </div>
</div>

<div class="featured">
    <div class="featured-menu">
        <a class="active" href="#">Популярные</a><a href="#">Новинки</a>
    </div>
    <a class="explore" href="#">показать все <img src="{% static 'img/arrow.png'%}" alt=""></a>
    <div class="clearfix">
    </div>
    <div class="tab-content">
        {% for product in object_list %}
        <div class="block">
            <a href="{% url 'basket:basket_add' product.pk %}"><img src="/media/{{ product.image }}" alt="" width="100%">
                <div class="text">
                    <img src="{% static 'img/icon-hover.png' %}" alt="img">
                    <h4>{{ product.name }}</h4>
                    <p>{{ product.category.name }}</p>
                    <p>{{ product.short_desc }}</p>
                </div>
            </a>
        </div>
        {% endfor  %}
    </div>
</div>
{% endblock %}

mainapp/templates/mainapp/product.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block content %}
    <div class="hero-white">
        <div class="header clearfix">
            {% include 'mainapp/includes/inc_main_menu.html' %}
        </div>
    </div>
    <div class="details">
        {% include 'mainapp/includes/inc_products_category.html' %}

        <div class="details-products">
            <div class="details-slider">
                <div class="slider-product">
                    <img src="/media/{{ product.image }}"
                         alt="{{ product.short_desc }}" width="100%">
                </div>
                <div class="slider-control">
                    <div class="block">
                        <a href="#">
                            <img src="/media/{{ product.image }}" alt="вариант 1" style="border: solid gray 1px">
                        </a>
                    </div>
                    <div class="block">
                        <a href="#">
                            <img src="/media/{{ product.image }}" alt="вариант 2" style="border: solid gray 1px">
                        </a>
                    </div>
                    <div class="block">
                        <a href="#">
                            <img src="/media/{{ product.image }}" alt="вариант 3" style="border: solid gray 1px">
                        </a>
                    </div>
                </div>
            </div>

            <div class="description">
                <h3 class="big-bold">{{ product.name | capfirst }}</h3>
                <br>
                <p class="price"> {{ product.price|floatformat:2 }} <span>руб</span></p>
                <a href="{% url 'basket:basket_add' product.pk %}" class="red-button">
                    Добавить в корзину
                    <i class="fa fa-chevron-right" aria-hidden="true"></i>
                </a>
                <div class="description-text">
                    {{ product.description }}
                </div>
            </div>
        </div>

    </div>

    <div class="clr"></div>

{% endblock %}

mainapp/templates/mainapp/products.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% load mainapp_tags %}
{% block content %}
    <div class="hero-white">
        <div class="header clearfix">
            {% include 'mainapp/includes/inc_main_menu.html' %}
        </div>
    </div>

    <div class="details">
        {% include 'mainapp/includes/inc_products_category.html' %}

        <div class="details-products">
            <div class="details-slider">
                <div class="slider-product">
                    <img src="{{ hot_product.image|product_image }}" alt="" width = 100%>
                </div>
                <div class="slider-control">
                    <div class="block">
                        <a href="#"><img src="{{ hot_product.image|product_image }}" alt="" style="border: solid gray 1px">
                            <div class="text"></div>
                        </a>
                    </div>
                    <div class="block">
                        <a href="#"><img src="{{ hot_product.image|product_image }}" alt="" style="border: solid gray 1px">
                            <div class="text"></div>
                        </a>
                    </div>
                    <div class="block">
                        <a href="#"><img src="{{ hot_product.image|product_image }}" alt="" style="border: solid gray 1px">
                            <div class="text"></div>
                        </a>
                    </div>
                </div>
            </div>

            <div class="description">
                <h3 class="big-bold">{{ hot_product.name|capfirst }}</h3>
                <h3 class="red">горячее предложение</h3>
                <p class="price"> {{ hot_product.price|floatformat:2 }} <span>руб</span></p>
                <a href="{% url 'basket:basket_add' hot_product.pk %}" class="red-button">
                    Добавить в корзину <i class="fa fa-chevron-right" aria-hidden="true"></i>
                </a>
                <div class="description-text">
                    <p>{{ hot_product.description }}</p>
                </div>
            </div>
        </div>

        <div class="related">
            <div class="title clearfix">
                <h2>Похожие продукты</h2>
                <a class="explore" href="#">показать все <img src="{% static 'img/arrow.png' %}" alt=""></a>
            </div>
            <div class="related-products clearfix">
                {% for product in same_products %}
                    <div class="block">
                        <a href="{% url 'products:product' product.pk %}">
                            <img src="{{ product.image|product_image }}" alt="" width="100%">
                            <div class="text">
                                <img src="{% static 'img/icon-hover.png' %}" alt="img">
                                <h4>{{ product.name|capfirst }}</h4>
                                <p>{{ product.category.name|capfirst }}</p>
                                <p>{{ product.short_desc }}</p>
                            </div>
                        </a>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

mainapp/templates/mainapp/products_list.html
{% extends 'mainapp/base.html' %}
{% load mainapp_tags %}
{% load static %}
{% block content %}
    <div class="hero-white">
        <div class="header clearfix">
            {% include 'mainapp/includes/inc_main_menu.html' %}
            <a href="#" class="basket"></a>
        </div>
    </div>

    <div class="details">
        {% include 'mainapp/includes/inc_products_category.html' %}
        <div class="products_list">
            <div class="title clearfix">
                <h2>
                    Категория: "{{ category.name|title }}"
                </h2>
                <div class="paginator">
                    {% if products.has_previous %}
                        <a href="{% url 'products:product_paginate' category.pk products.previous_page_number %}"><</a>
                    {% endif %}
                    <span class="current-app">Страница {{ products.number }} из {{ products.paginator.num_pages }}</span>
                    {% if products.has_next %}
                        <a href="{% url 'products:product_paginate' category.pk products.next_page_number %}">></a>
                    {% endif %}
                </div>
            </div>
            <div class="category-products clearfix">

                {% for product in products %}
                    <div class="block" style="margin-right: 30px; margin-bottom: 30px">
                        <a href="{% url 'products:product' product.pk %}">
{#                            <img src="/media/{{ product.image }}" alt="product" width="100%">#}
                            <img src="{{ product.image|product_image }}" alt="product" width="100%">
                            <div class="text">
                                <img src="{% static 'img/icon-hover.png' %}" alt="hover">
                                <h4>{{ product.name }}</h4>
                                <p>{{ product.description }}</p>
                            </div>
                        </a>
                    </div>
                {% endfor %}

            </div>
        </div>
    </div>
{% endblock %}